### ISSUE TITLE
How to activate the tailwind_error_tag/2 helper

### ISSUE THREAD

**Issue by wintermeyer** [wintermeyer/phx_tailwind_generators#2]
In `lib/mix/tasks/phx_gen_tailwind.ex` line 200 the following code can be found:

    defp error(field) do
      # ~s(<%= PhxTailwindGenerators.tailwind_error_tag f, #{inspect(field)} %>)
    end

I don't know how to make `PhxTailwindGenerators.tailwind_error_tag` or better just `tailwind_error_tag` work. That's the reason why it is commented out. But I'd like to make it work.

The helper function is defined in `lib/phx_tailwind_generators.ex` but commented out because I don't know how to import `ErrorHelpers` and if this is the right file to host this function.

```elixir
  # import ??????????????.ErrorHelpers

  # def tailwind_error_tag(form, field) do
  #   Enum.map(Keyword.get_values(form.errors, field), fn error ->
  #     content_tag(:p, translate_error(error),
  #       class: "mt-2 text-sm text-red-500",
  #       phx_feedback_for: input_name(form, field)
  #     )
  #   end)
  # end
```

**Comment by JEG2** [comment]
Hey @wintermeyer.

The generator approach is more to write the helper functions into their projects, so it's seamless with their project and can be tailored to their needs.  As you correct discovered, you can really determine which code is calling yours and it wouldn't be fair to use their `…ErrorHelpers` if you did.  They may have deleted it, renamed it, or made incompatible modifications to it.  Post generation, it's their code.

Could you just write your helper into that same file?

**Comment by wintermeyer** [comment]
> Could you just write your helper into that same file?

I tried that today. It led me into a rabbit whole of functions which are all in Phoenix already that was way over my head. I couldn't solve it.

**Comment by wintermeyer** [comment]
I created a question on stackoverflow. https://stackoverflow.com/questions/65787793/helper-function-within-a-hex-package

**Comment by JEG2** [comment]
I was thinking of something like this, in case it helps:

```Elixir
{a, b, c} = :erlang.now()
n = node()
filename = List.flatten(:io_lib.format("~p-~p.~p.~p.exs", [n, a, b, c])) |> to_string()

temp_path = System.tmp_dir!() |> Path.join(filename)
File.open!(temp_path, [:write], fn f ->
  path_to_phx_file # FIXME
  |> File.stream!()
  |> Enum.each(fn line ->
     if line =~ ~r{def\s+error_tag} do
      IO.write(f, "Your code here…")
     end
     IO.write(f, line)
  end)
end)

File.rename!(temp_path, path_to_phx_file)
```

**Comment by wintermeyer** [comment]
Fixed by https://github.com/wintermeyer/phx_tailwind_generators/commit/28e99e6ab668b070ace40fa43b6979e0c3a1efbe
